apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
namespace: argocd
images:
- name: the-my-app
- newName: 440953937617.dkr.ecr.us-east-2.amazonaws.com/opsera-nexus-integrator
  newTag: v1
